# Cloud Build configuration for MyNewsRobot
# Builds Docker image and deploys to Cloud Run

steps:
    # Build the container image
    - name: "gcr.io/cloud-builders/docker"
      args:
          - "build"
          - "-t"
          - "gcr.io/$PROJECT_ID/mynewsrobot:$COMMIT_SHA"
          - "-t"
          - "gcr.io/$PROJECT_ID/mynewsrobot:latest"
          - "."

    # Push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args:
          - "push"
          - "gcr.io/$PROJECT_ID/mynewsrobot:$COMMIT_SHA"

    - name: "gcr.io/cloud-builders/docker"
      args:
          - "push"
          - "gcr.io/$PROJECT_ID/mynewsrobot:latest"

    # Deploy to Cloud Run (optional - enable in Phase 5)
    # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    #   entrypoint: gcloud
    #   args:
    #     - 'run'
    #     - 'deploy'
    #     - 'mynewsrobot'
    #     - '--image'
    #     - 'gcr.io/$PROJECT_ID/mynewsrobot:$COMMIT_SHA'
    #     - '--region'
    #     - 'us-central1'
    #     - '--platform'
    #     - 'managed'
    #     - '--allow-unauthenticated'

images:
    - "gcr.io/$PROJECT_ID/mynewsrobot:$COMMIT_SHA"
    - "gcr.io/$PROJECT_ID/mynewsrobot:latest"

options:
    machineType: "N1_HIGHCPU_8"
    logging: CLOUD_LOGGING_ONLY

timeout: "1200s"
